# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SgInd1 <- function(X, W) {
    .Call('plac_SgInd1', PACKAGE = 'plac', X, W)
}

PwInd1 <- function(X, W) {
    .Call('plac_PwInd1', PACKAGE = 'plac', X, W)
}

TvInd1 <- function(Zv, W) {
    .Call('plac_TvInd1', PACKAGE = 'plac', Zv, W)
}

BetaTv2 <- function(ZFV_, Z, X, Ind1, Ind2, b, h) {
    .Call('plac_BetaTv2', PACKAGE = 'plac', ZFV_, Z, X, Ind1, Ind2, b, h)
}

LambdaTv2 <- function(Z, X, Ind1, Ind2, Dn, b, h) {
    .Call('plac_LambdaTv2', PACKAGE = 'plac', Z, X, Ind1, Ind2, Dn, b, h)
}

SWE_Tv2 <- function(ZFV_, Z, X, W, Ind1, Ind2, b, h) {
    .Call('plac_SWE_Tv2', PACKAGE = 'plac', ZFV_, Z, X, W, Ind1, Ind2, b, h)
}

PLAC_Tv3 <- function(Z, ZFV_, X, W, Ind1, Ind2, Dn, b, h, K = 100L) {
    .Call('plac_PLAC_Tv3', PACKAGE = 'plac', Z, ZFV_, X, W, Ind1, Ind2, Dn, b, h, K)
}

TvInd2 <- function(PD, Zv, W) {
    .Call('plac_TvInd2', PACKAGE = 'plac', PD, Zv, W)
}

TvInd3 <- function(PD, Zv, W) {
    .Call('plac_TvInd3', PACKAGE = 'plac', PD, Zv, W)
}

BetaTvR1 <- function(ZF, ZFV_, Z, X, Ind1, Ind2, b, h) {
    .Call('plac_BetaTvR1', PACKAGE = 'plac', ZF, ZFV_, Z, X, Ind1, Ind2, b, h)
}

LambdaTvR1 <- function(ZF, Z, X, Ind1, Ind2, Dn, b, h) {
    .Call('plac_LambdaTvR1', PACKAGE = 'plac', ZF, Z, X, Ind1, Ind2, Dn, b, h)
}

SWE_TvR1 <- function(ZF, ZFV_, Z, X, W, Ind1, Ind2, b, h) {
    .Call('plac_SWE_TvR1', PACKAGE = 'plac', ZF, ZFV_, Z, X, W, Ind1, Ind2, b, h)
}

PLAC_TvR1 <- function(ZF, ZFV_, Z, X, W, Ind1, Ind2, Dn, b, h, K = 100L) {
    .Call('plac_PLAC_TvR1', PACKAGE = 'plac', ZF, ZFV_, Z, X, W, Ind1, Ind2, Dn, b, h, K)
}

