# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate risk-set indicators
#'
#' @param X the response matrix (As, Xs, Ds).
#' @param W the ordered observed event times.
#' @return risk-set indicators Y_i(w_k) of the form I(A_i <= w_k <= X_i).
#' @export
SgInd1 <- function(X, W) {
    .Call('plac_SgInd1', PACKAGE = 'plac', X, W)
}

#' Generate truncation-pair indicators
#'
#' @param X the response matrix (As, Xs, Ds).
#' @param W the ordered observed event times.
#' @return the truncation-pair indicators of the form I(w_k <= A_i)
#' - I(w_k <= XA_j).
#' @export
PwInd1 <- function(X, W) {
    .Call('plac_PwInd1', PACKAGE = 'plac', X, W)
}

#' Generate time-depependent covariate indicators
#'
#' @param Zv the jump time.
#' @param W the ordered observed event times.
#' @return the time-depependent covariate indicators of the form I(w_k > zeta).
#' @export
TvInd1 <- function(Zv, W) {
    .Call('plac_TvInd1', PACKAGE = 'plac', Zv, W)
}

LambdaTv2 <- function(Z, X, Ind1, Ind2, Dn, b, h) {
    .Call('plac_LambdaTv2', PACKAGE = 'plac', Z, X, Ind1, Ind2, Dn, b, h)
}

SWE_Tv2 <- function(ZFV_, Z, X, W, Ind1, Ind2, b, h) {
    .Call('plac_SWE_Tv2', PACKAGE = 'plac', ZFV_, Z, X, W, Ind1, Ind2, b, h)
}

PLAC_Tv3 <- function(Z, ZFV_, X, W, Ind1, Ind2, Dn, b, h, K = 100L) {
    .Call('plac_PLAC_Tv3', PACKAGE = 'plac', Z, ZFV_, X, W, Ind1, Ind2, Dn, b, h, K)
}

TvInd2 <- function(PD, Zv, W) {
    .Call('plac_TvInd2', PACKAGE = 'plac', PD, Zv, W)
}

TvInd3 <- function(PD, Zv, W) {
    .Call('plac_TvInd3', PACKAGE = 'plac', PD, Zv, W)
}

BetaTvR1 <- function(ZF, ZFV_, Z, X, Ind1, Ind2, b, h) {
    .Call('plac_BetaTvR1', PACKAGE = 'plac', ZF, ZFV_, Z, X, Ind1, Ind2, b, h)
}

LambdaTvR1 <- function(ZF, Z, X, Ind1, Ind2, Dn, b, h) {
    .Call('plac_LambdaTvR1', PACKAGE = 'plac', ZF, Z, X, Ind1, Ind2, Dn, b, h)
}

SWE_TvR1 <- function(ZF, ZFV_, Z, X, W, Ind1, Ind2, b, h) {
    .Call('plac_SWE_TvR1', PACKAGE = 'plac', ZF, ZFV_, Z, X, W, Ind1, Ind2, b, h)
}

PLAC_TvR1 <- function(ZF, ZFV_, Z, X, W, Ind1, Ind2, Dn, b, h, K = 100L) {
    .Call('plac_PLAC_TvR1', PACKAGE = 'plac', ZF, ZFV_, Z, X, W, Ind1, Ind2, Dn, b, h, K)
}

